# Generated by Django 4.2 on 2024-07-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_fees_detail_fees_receipt_fees_detail_semester_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Student',
            field=models.OneToOneField(limit_choices_to={'role': 'S'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
