# Generated by Django 4.2 on 2024-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_detail',
            name='reference_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
