# Generated by Django 4.2 on 2024-08-01 18:08

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_student_type_of_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=students.models.student_profile_image_directory),
        ),
    ]
